const tagDict = new Map([
	["toán", "Toán học"],
	["maths", "Toán học"],
	["math", "Toán học"],
	["lý", "Vật lý"],
	["lí", "Vật lý"],
	["vật lí", "Vật lý"],
	["lý học", "Vật lý"],
	["lí học", "Vật lý"],
	["physics", "Vật lý"],
	["physic", "Vật lý"],
	["hóa", "Hóa học"],
	["chemistry", "Hóa học"],
	["chem", "Hóa học"],
	["sinh", "Sinh học"],
	["biology", "Sinh học"],
	["bio", "Sinh học"],
	["sử", "Lịch sử"],
	["history", "Lịch sử"],
	["địa lí", "Địa lý"],
	["địa", "Địa lý"],
	["geography", "Địa lý"],
	["geo", "Địa lý"],
	["văn", "Văn học"],
	["ngữ văn", "Văn học"],
	["literature", "Văn học"],
	["khác", "Lĩnh vực khác"],
	["other", "Lĩnh vực khác"],
	["others", "Lĩnh vực khác"],
	["khoa học máy tính", "Tin học"],
	["computer science", "Tin học"],
	["art", "Nghệ thuật"],
	["arts", "Nghệ thuật"],
	["âm nhạc", "Nghệ thuật"],
	["hbc", "Hiểu biết chung"],
	["general knowledge", "Hiểu biết chung"],
	["general", "Hiểu biết chung"],
	["sport", "Thể thao"],
	["sports", "Thể thao"],
	["english", "Tiếng Anh"],
	["anh", "Tiếng Anh"],
	["câu hỏi tiếng anh", "Tiếng Anh"],
	["anh văn", "Tiếng Anh"],
	["ngoại ngữ", "Tiếng Anh"],
	["kđ", "Khởi động"],
	["start", "Khởi động"],
	["vđ", "Về đích"],
	["finish", "Về đích"],
	["vcnv", "Vượt chướng ngại vật"],
	["cnv", "Vượt chướng ngại vật"],
	["chướng ngại vật", "Vượt chướng ngại vật"],
	["obstacle", "Vượt chướng ngại vật"],
	["obs", "Vượt chướng ngại vật"],
	["chp", "Câu hỏi phụ"],
]);

const otherDict = new Map([
	["politics", "Lĩnh vực khác"],
	["pháp luật", "Lĩnh vực khác"],
	["luật pháp", "Lĩnh vực khác"],
	["chính trị", "Lĩnh vực khác"],
	["law", "Lĩnh vực khác"],
	["khoa học", "Lĩnh vực khác"],
	["thiên văn", "Lĩnh vực khác"],
]);

module.exports = {tagDict, otherDict};